### describe() : 기술통계 확인하기

수치형 데이터 기술통계 확인하기

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_analysis_adv-main/datasets/bookings/Bookings.csv')

df.describe()

           Rating
count  315.000000
mean     7.883492
std      0.885183
min      1.000000
25%      7.500000
50%      8.000000
75%      8.400000
max     10.000000

범주형 데이터 기술통계 확인하기

In [3]:
'''
object 타입에 해당하는 열 출력

각 열 내에 있는 '행 개수(null 포함)', '행 개수 중에서도 유니크한 값', '가장 많이 등장하는 행 값', '많이 등장하는 행 값의 빈도수'
'''

df.describe(include = 'object')

                            Hotel_Name      Review Total_Review    Location
count                              525         325          325         525
unique                             498           8          255          25
top     Oakwood Residence Midtown East  Very good      1 review  Manhattan
freq                                 2         117            5         112

### value_counts() : 범주형 데이터에 있는 정보 확인

In [7]:
# 'Review' 칼럼에 있는 데이터 확인하기
  # null 값은 제외하고 값이 출력된다

df['Review'].value_counts()

Review
Very good         117
Good              116
Review score       31
Fabulous           30
Superb             16
Superb 9.0          8
Exceptional         5
Exceptional 10      2
Name: count, dtype: int64

In [30]:
'''

df.loc[df['Review'] == 'Superb 9.0', 'Review'] = 'Superb '

▶ 작성순서
df에 있는 'Review' 열 내에 있는 'Superb 9.0'를 'Superb '로 바꾸겠다
  df.loc[df['Review'] == Superb 9.0] = 'Superb '
이때 결과 값은 Review 열만 보이게 하고 싶슾니다.
  df.loc[df['Review'] == Superb 9.0, 'Review'] = 'Superb '
변경한 걸 다시 저장합니다.
  df.loc[df['Review'] == 'Superb 9.0', 'Review'] = 'Superb '

'''


df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_analysis_adv-main/datasets/bookings/Bookings.csv')
df['Review'].value_counts()

# Review 칼럼 내에 있는 Superb 9.0를 Superb 값에 통합하기
df.loc[df['Review'] == 'Superb 9.0', 'Review'] = 'Superb '
df['Review'].value_counts()

# Review 칼럼 내에 있는 Exceptional 10를 Exceptional 값에 통합하기
df.loc[df['Review'] == 'Exceptional 10', 'Review'] = 'Exceptional '
df['Review'].value_counts()

Review
Very good        117
Good             116
Review score      31
Fabulous          30
Superb            24
Exceptional        7
Name: count, dtype: int64

### unique() : 유니크한 값만 확인하기

map(lambda) 이용해서 각 행에 있는 값 변경하기

In [46]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_analysis_adv-main/datasets/bookings/Bookings.csv')
df['Total_Review'].unique()

# 쉼표(,) 제거 하기
# df['Total_Review'].map(replace(',',''))
df['Total_Review'] = df['Total_Review'].map(lambda x : str(x).replace(',',''))

# review 제거하기
df['Total_Review'] = df['Total_Review'].map(lambda x : str(x).replace('review', '').strip())


# external 제거하기
df['Total_Review'] = df['Total_Review'].map(lambda x : str(x).replace('external', '').strip())

df['Total_Review'].unique()

array(['28', '52', '2870', '975', '13951', '8044', '16148', '343', '6038',
       '2028', '9659', '4435', '7298', '11455', '2802', '1847', '2189',
       '703', '1382', '4646', '951', '4498', '1475', '6245', '5866',
       '959', '1876', '848', '3097', '3477', '1648', '46', '2289', '148',
       '664', '1867', '1067', '130', '920', '2560', '3878', '1698', '719',
       '7585', '1180', '2035', '6144', '638', '9240', '3907', '3128',
       '2383', '833', '558', '3170', '2857', '981', '192', '1449', '1373',
       '598', '3859', '3639', '1048', '2859', '2412', '749', '6639',
       '1143', '2353', '3002', '8844', '57', '657', '2535', '946', '1087',
       '3627', '844', '483', '1078', '1074', '1797', '728', '415', '766',
       '523', '770', '178', '464', '647', '1225', '562', '1', '1188',
       '1260', '4246', '2521', '586', '1643', '1243', '2623', '621',
       '488', '607', '1425', '1389', '2014', '1000', '2299', '595', '751',
       '159', '1550', '1030', '4166', '1089', 'nan', '663', '579', '1864',
       '377', '832', '718', '1294', '3255', '495', '1736', '1918', '333',
       '234', '114', '2620', '754', '1105', '94', '1097', '2446', '665',
       '1169', '2717', '988', '1046', '321', '317', '108', '76', '721',
       '1420', '1519', '49', '407', '193', '4092', '965', '307', '2317',
       '2982', '3832', '269', '1834', '707', '425', '390', '985', '693',
       '1218', '113', '1122', '966', '711', '1220', '13', '2533', '233',
       '14', '553', '601', '532', '65', '1592', '855', '400', '386',
       '1092', '259', '411', '865', '3471', '723', '525', '943', '1500',
       '325', '1708', '230', '227', '1778', '53', '4288', '787', '355',
       '1251', '128', '258', '125', '699', '285', '109', '30', '1754',
       '437', '60', '200', '2', '453', '769', '465', '6', '524', '434',
       '372', '817', '472', '314', '168', '1085', '1195', '1118', '1471',
       '416', '173', '352', '385', '1482', '22', '241', '497', '117',
       '59', '79', '3', '379', '42', '255', '99', '212', '602', '9',
       '165', '146', '7', '4'], dtype=object)

astype(), describe() : 데이터타입 변경 후 기술통계 확인하기

In [48]:
df['Total_Review'] = df['Total_Review'].astype('float')
df['Total_Review'].info()
df['Total_Review'].describe()

<class 'pandas.core.series.Series'>
RangeIndex: 525 entries, 0 to 524
Series name: Total_Review
Non-Null Count  Dtype
--------------  -----
325 non-null    float64
dtypes: float64(1)
memory usage: 4.2 KB

count      325.000000
mean      1771.630769
std       2530.013514
min          1.000000
25%        343.000000
50%        920.000000
75%       2189.000000
max      16148.000000
Name: Total_Review, dtype: float64